name: versions

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
        
      - name: Install requirements
        run: |
          pip install -U pip wheel
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
    
